version: "3"

services:
  pongo_a:
    build:
      context: .
    image: wx/pongo:latest
    command: pongo broker --id 0 --raft-addr=pongo_a:9093 --bootstrap --bootstrap-expect=3

  pongo_b:
    build:
      context: .
    image: wx/pongo:latest
    command: pongo broker --join=pongo_a:9094 --id 1 --raft-addr=pongo_b:9093 --bootstrap-expect=3

  pongo_c:
    build:
      context: .
    image: wx/pongo:latest
    command: pongo broker --join=pongo_a:9094 --id 2 --raft-addr=pongo_c:9093 --bootstrap-expect=3
